import { COLOR } from "@/theme/theme";

export const styles = {
  modalOverride: {
    width: "fit-content",
    maxWidth: "calc(100vw - 24px)",
    padding: 0,
    overflow: "hidden" as const,
    borderRadius: 18,
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
  },
  modalWrapper: {
    display: "flex",
    width: "100%",
    background: COLOR.BACKGROUND.SECONDARY,
    height: 580,
    maxHeight: "90vh",
    overflowY: "auto" as const,
    boxSizing: "border-box" as const,
  },
  // Left Column: Settings
  settingsColumn: {
    display: "flex",
    flexDirection: "column" as const,
    padding: "20px 22px",
    overflowY: "auto" as const,
    height: "100%",
    maxHeight: "100%",
    gap: 16,
    boxSizing: "border-box" as const,
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
    margin: 0,
    letterSpacing: "-0.02em",
  },
  headerRightActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  closeIconButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: "50%",
    border: "none",
    background: COLOR.BACKGROUND.SUBTLE,
    color: COLOR.TEXT.SECONDARY,
    cursor: "pointer",
    transition: "all 150ms ease",
  },
  // Contact Section
  contactSection: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  contactInputsRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  clientSection: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  clientCard: {
    height: 37,
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    padding: "0 2px",
    boxSizing: "border-box" as const,
  },
  clientAvatarWrap: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "rgba(0, 128, 162, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  clientInfo: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 1,
    minWidth: 0,
    flex: 1,
  },
  clientLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    color: COLOR.TEXT.TERTIARY,
    letterSpacing: "0.05em",
  },
  clientName: {
    fontSize: 13.5,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  clientNameEmpty: {
    fontSize: 13,
    fontWeight: 500,
    color: COLOR.TEXT.TERTIARY,
    fontStyle: "italic" as const,
  },
  contactField: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  fieldLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    color: COLOR.TEXT.TERTIARY,
    letterSpacing: "0.05em",
  },
  contactInput: {
    width: "100%",
    height: 37,
    background: COLOR.BACKGROUND.PRIMARY,
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    borderRadius: 8,
    padding: "8px 12px",
    fontSize: 13,
    fontWeight: 500,
    color: COLOR.TEXT.PRIMARY,
    outline: "none",
    boxSizing: "border-box" as const,
    transition: "border-color 150ms ease",
  },
  // Backward compatibility
  clientDisplay: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 7,
    boxSizing: "border-box" as const,
  },
  clientDisplayText: {
    fontSize: 14,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  clientDisplayEmpty: {
    fontSize: 13,
    fontWeight: 500,
    color: COLOR.TEXT.TERTIARY,
    fontStyle: "italic" as const,
  },
  // Items List
  sectionContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 10.5,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    color: COLOR.TEXT.TERTIARY,
    letterSpacing: "0.05em",
    margin: 0,
  },
  itemsList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  itemRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 10,
    cursor: "pointer",
    transition: "all 150ms ease",
    userSelect: "none" as const,
  },
  itemRowActive: {
    background: "rgba(0, 128, 162, 0.08)",
    border: "1px solid rgba(0, 128, 162, 0.25)",
  },
  itemRowInactive: {
    background: "transparent",
    border: "1px solid transparent",
  },
  itemIconPill: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "all 150ms ease",
  },
  itemIconPillActive: {
    background: "rgba(0, 128, 162, 0.15)",
    color: COLOR.ACCENT.PRIMARY,
  },
  itemIconPillInactive: {
    background: COLOR.BACKGROUND.PRIMARY,
    color: COLOR.TEXT.SECONDARY,
  },
  itemTextCol: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: 600,
    margin: 0,
    lineHeight: 1.2,
  },
  itemDescription: {
    fontSize: 11,
    color: COLOR.TEXT.SECONDARY,
    margin: 0,
    lineHeight: 1.2,
  },
  checkboxBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    border: "2px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "all 150ms ease",
  },
  checkboxBoxActive: {
    background: COLOR.ACCENT.PRIMARY,
    borderColor: COLOR.ACCENT.PRIMARY,
    color: "#ffffff",
  },
  checkboxBoxInactive: {
    background: "#ffffff",
    borderColor: COLOR.BORDER.DEFAULT,
    color: "transparent",
  },
  // Submit WhatsApp Button
  submitButton: {
    width: "100%",
    padding: "13px 18px",
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 600,
    color: COLOR.TEXT.CONTRAST,
    background: COLOR.ACCENT.PRIMARY,
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
    transition: "all 150ms ease",
    marginTop: "auto",
  },
  submitButtonHover: {
    background: COLOR.ACCENT.HOVER,
    boxShadow: "0 4px 12px rgba(0, 128, 162, 0.25)",
    transform: "translateY(-1px)",
  },
  // Right Column: Live Phone Mockup or Wide Editor (Fixed Height)
  previewColumn: {
    background: COLOR.BACKGROUND.PRIMARY,
    padding: "18px 20px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative" as const,
    height: "100%",
    maxHeight: "100%",
    overflowY: "hidden" as const,
    boxSizing: "border-box" as const,
  },
  previewHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 380,
    height: 28,
    marginBottom: 12,
    gap: 8,
    flexShrink: 0,
  },
  previewColumnHeader: {
    fontSize: 12,
    fontWeight: 600,
    color: COLOR.TEXT.SECONDARY,
    margin: 0,
    letterSpacing: "0.02em",
  },
  modeSwitchGroup: {
    display: "flex",
    alignItems: "center",
    background: "#ffffff",
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    borderRadius: 20,
    padding: 3,
    gap: 2,
  },
  modeSwitchBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    fontWeight: 500,
    color: COLOR.TEXT.SECONDARY,
    background: "transparent",
    border: "none",
    borderRadius: 14,
    padding: "4px 10px",
    cursor: "pointer",
    transition: "all 150ms ease",
  },
  modeSwitchBtnActive: {
    background: COLOR.ACCENT.PRIMARY,
    color: "#ffffff",
    fontWeight: 600,
  },
  // Phone Mockup (Formato Mode - Fixed 500px Height)
  phoneFrame: {
    width: "100%",
    maxWidth: 340,
    height: 500,
    minHeight: 500,
    maxHeight: 500,
    background: "#1e293b",
    border: "6px solid #1e293b",
    borderRadius: 30,
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.25), 0 8px 10px -6px rgba(0, 0, 0, 0.2)",
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden" as const,
    boxSizing: "border-box" as const,
    flexShrink: 0,
  },
  notch: {
    position: "absolute" as const,
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: 90,
    height: 13,
    background: "#1e293b",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    zIndex: 20,
  },
  phoneScreen: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    background: "#EFEAE2",
    overflow: "hidden" as const,
  },
  // WhatsApp Chat Header
  whatsappHeader: {
    background: "#075E54",
    padding: "14px 12px 10px 12px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: "#ffffff",
    zIndex: 10,
  },
  whatsappAvatar: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    background: "#ffffff2e",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    flexShrink: 0,
  },
  whatsappHeaderInfo: {
    display: "flex",
    flexDirection: "column" as const,
    minWidth: 0,
    flex: 1,
  },
  whatsappContactName: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "#ffffff",
    whiteSpace: "nowrap" as const,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
  },
  whatsappStatus: {
    fontSize: 9.5,
    color: "#86efac",
  },
  // WhatsApp Chat Wallpaper & Message Bubble
  chatArea: {
    flex: 1,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
    gap: 8,
    position: "relative" as const,
  },
  bubble: {
    background: "#E1FFC7",
    borderRadius: "10px 0px 10px 10px",
    padding: "10px 12px 6px 12px",
    boxShadow: "0 1px 1px rgba(0, 0, 0, 0.12)",
    maxWidth: "96%",
    alignSelf: "flex-end" as const,
    position: "relative" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
  },
  // Bubble Formatted View
  bubbleFormattedContainer: {
    display: "flex",
    flexDirection: "column" as const,
    cursor: "pointer",
    userSelect: "text" as const,
    width: "100%",
  },
  bubbleFormattedContent: {
    fontSize: 12.5,
    lineHeight: 1.48,
    color: "#111827",
    fontFamily: "var(--font-geist-sans), -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    wordBreak: "break-word" as const,
  },
  clickToEditBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start" as const,
    fontSize: 9.5,
    fontWeight: 600,
    color: "#075E54",
    background: "rgba(7, 94, 84, 0.1)",
    padding: "2px 7px",
    borderRadius: 5,
    marginTop: 6,
    transition: "all 150ms ease",
    userSelect: "none" as const,
  },
  bubbleFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 3,
    alignSelf: "flex-end" as const,
    marginTop: 2,
  },
  bubbleTime: {
    fontSize: 10,
    color: "#6b7280",
  },
  doubleCheck: {
    color: "#34B7F1",
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1,
  },
  // Wide Edit Card (Edit Mode - Fixed 500px Height)
  wideEditCard: {
    width: "100%",
    maxWidth: 380,
    height: 500,
    minHeight: 500,
    maxHeight: 500,
    background: "#ffffff",
    border: `1px solid ${COLOR.BORDER.SUBTLE}`,
    borderRadius: 16,
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.05)",
    padding: "16px 16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    position: "relative" as const,
    boxSizing: "border-box" as const,
    flexShrink: 0,
  },
  wideEditHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 8,
    borderBottom: `1px solid ${COLOR.BORDER.SUBTLE}`,
    gap: 8,
    flexShrink: 0,
  },
  wideEditRecipientBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
  },
  wideEditTip: {
    fontSize: 11,
    color: COLOR.TEXT.SECONDARY,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
  wideEditTextarea: {
    width: "100%",
    flex: 1,
    background: COLOR.BACKGROUND.PRIMARY,
    border: `1px solid ${COLOR.BORDER.DEFAULT}`,
    borderRadius: 10,
    padding: "12px 14px",
    fontSize: 13,
    lineHeight: 1.5,
    color: COLOR.TEXT.PRIMARY,
    outline: "none",
    resize: "none" as const,
    fontFamily: "var(--font-geist-sans), -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    boxSizing: "border-box" as const,
    transition: "border-color 150ms ease",
  },
  wideEditFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
    flexShrink: 0,
  },
  wideEditHint: {
    fontSize: 11,
    color: COLOR.TEXT.TERTIARY,
  },
  // Floating Action Buttons Group (Restablecer & Copiar)
  floatingActionsGroup: {
    position: "absolute" as const,
    bottom: 12,
    right: 12,
    zIndex: 30,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  wideEditActionsGroup: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginLeft: "auto",
  },
  actionButtonPill: {
    background: "#ffffff",
    border: `1px solid ${COLOR.BORDER.DEFAULT}`,
    borderRadius: 8,
    padding: "5px 11px",
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    fontWeight: 600,
    color: COLOR.TEXT.PRIMARY,
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.08)",
    transition: "all 150ms ease",
  },
  resetActionButton: {
    color: COLOR.ACCENT.PRIMARY,
    background: COLOR.BACKGROUND.INFO_TINT,
    border: `1px solid rgba(0, 128, 162, 0.25)`,
  },
  copyFloatingButtonCopied: {
    borderColor: "#16a34a",
    color: "#16a34a",
  },
  editedHint: {
    fontSize: 10.5,
    color: COLOR.TEXT.TERTIARY,
    textAlign: "center" as const,
    marginTop: 6,
  },
};
